title: Refinancing
description: Understand well of refinancing and implementing ASAP.
template:
  repo: refinancing-template
  name: refinancing
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
